### ISSUE TITLE
Implementar template para integração com data.rio

### ISSUE THREAD

**Issue by gabriel-milan** [prefeitura-rio/queries-datario#7]
### To-do List
- [x] Definir modelo de título
- [x] Implementar integração para o modelo de título @gabriel-milan 
- [x] Definir modelo de descrição
- [x] Implementar integração para o modelo de descrição @gabriel-milan 
- [x] Definir modelo de tags
- [x] Implementar integração para as tags @gabriel-milan 
- [x] Definir modelo de breve resumo
- [x] Implementar integração para o breve resumo do item @gabriel-milan 
- [x] Definir modelo dos termos de uso @JoaoCarabetta @fernandascovino @d116626 
- [x] Implementar integração para os termos de uso @gabriel-milan 
- [x] Definir modelo de créditos
- [x] Implementar integração para os créditos @gabriel-milan 
- [x] Definir se vai usar uma miniatura (imagem) @JoaoCarabetta 
- [x] Implementar integração para a miniatura @gabriel-milan 
- [x] Estudar possibilidade de indicar tamanho do dado @gabriel-milan 
- [x] Implementar integração para o tamanho do dado (não é possível) @gabriel-milan 
- [x] Implementar gerador de URL @d116626 @gabriel-milan 
- [x] Implementar integração para a URL @gabriel-milan 
- [x] Thumbnail do escritório @caiojacintho 
- [x] Descobrir como funcionam as categorias no data.rio @gabriel-milan 
- [x] Compartilhar com grupos ao invés de categorias
- [x] Criar coisas na pasta `public/`
- [x] Fazer termo de uso em link (exemplo: https://pcrj.maps.arcgis.com/home/item.html?id=dc94b29fc3594a5bb4d297bee0c9a3f2)
